### PR TITLE
Forward port setup commits to 25.x

### PR DESCRIPTION
**Pull request by ajtowns**
Forward port of #15 (report block script flags), #13 (disable mainnet/testnet), and #16 (heretical deployments).

### CODE REVIEW

**Comment by jamesob** [comment]
Curious, why not just rebase everything currently in inquition/24.0 on top of upstream/25.0?

**Comment by ajtowns** [comment]
> Curious, why not just rebase everything currently in inquition/24.0 on top of upstream/25.0?

That's what this is doing, except keeping soft-forks into separate PRs?

**Comment by ajtowns** [comment]
Ugh, cirrus is building the wrong commit: https://cirrus-ci.com/task/6009028673798144

```
git checkout FETCH_HEAD
Previous HEAD position was 785cd17 chainparams: Add support for renouncing an HereticalDeployment
HEAD is now at 9d1821b Merge 02b996b5023d143621117a0676feff9cdaad1f6e into 8825983716abbc4d9125c0ee44cf4a0a470a1a27
```

Should be merging 785cd17 not 02b996 :(

**Comment by jamesob** [comment]
Cirrus acting a fool, talking about concurrency limits...

**Comment by ajtowns** [comment]
> Cirrus acting a fool, talking about concurrency limits...

Yeah, just doing these couple of PRs (11 builds total by the looks) has already exceeded the monthly [compute limits](https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/) that they're introducing tomorrow-ish.

**Comment by fanquake** [comment]
Speaking of, we definitely need to get some of the recent CI changes backported to our current releases branches.

**Pull request merged**
